# Generated by Django 5.2.3 on 2025-11-26 03:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
        ('productos', '0004_producto_organizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.moneda', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.CreateModel(
            name='ProductoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_especial', models.DecimalField(blank=True, decimal_places=2, help_text='Dejar vacío para usar el precio del artículo', max_digits=10, null=True, verbose_name='Precio Especial')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_productos', to='articulos.articulo', verbose_name='Artículo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Artículo del Producto',
                'verbose_name_plural': 'Artículos del Producto',
                'unique_together': {('producto', 'articulo')},
            },
        ),
    ]
