# Generated by Django 5.2.5 on 2025-10-04 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_initial'),
        ('productos', '0003_alter_producto_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.moneda'),
        ),
    ]
