# Generated by Django 5.2.3 on 2025-11-18 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_detallefactura_moneda'),
        ('organizaciones', '0002_organizacion_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='organizaciones.organizacion'),
        ),
    ]
