# Generated by Django 5.2.5 on 2025-10-04 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.moneda', verbose_name='Moneda'),
        ),
    ]
