# Generated by Django 5.2.3 on 2025-11-26 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('organizaciones', '0003_alter_miembro_role'),
        ('proveedores', '0002_proveedor_organizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=5)),
                ('cambio_a_usd', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('principal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo')),
                ('stock', models.IntegerField(verbose_name='Stock disponible')),
                ('stock_minimo', models.IntegerField(default=5, verbose_name='Stock mínimo')),
                ('activo', models.BooleanField(default=True, help_text='Desmarque para desactivar el artículo sin eliminarlo', verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria', verbose_name='Categoría')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='organizaciones.organizacion')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulos.moneda', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CodigoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('codigo_barra', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='articulos.articulo')),
            ],
            options={
                'verbose_name': 'Código de Artículo',
                'verbose_name_plural': 'Códigos de Artículo',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitir_multimoneda', models.BooleanField(default=False)),
                ('moneda_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulos.moneda')),
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
                'verbose_name_plural': 'Configuraciones de Tienda',
            },
        ),
    ]
