services:
  - type: web
    name: sistema-facturacion
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-facturacion-db
          property: connectionString

databases:
  - name: sistema-facturacion-db
    plan: free
