# Generated by Django 5.2.5 on 2025-09-19 20:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pedido')),
                ('fecha_esperada', models.DateField(verbose_name='Fecha Esperada de Entrega')),
                ('fecha_recibido', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('en_camino', 'En Camino'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total del Pedido')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas del Pedido')),
            ],
            options={
                'verbose_name': 'Pedido a Proveedor',
                'verbose_name_plural': 'Pedidos a Proveedores',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('iva', models.DecimalField(decimal_places=2, default=16, max_digits=5, verbose_name='IVA (%)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proveedores.pedidoproveedor')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('nombre_contacto', models.CharField(max_length=100, verbose_name='Nombre de Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(default='México', max_length=100, verbose_name='País')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC')),
                ('tipo_proveedor', models.CharField(choices=[('productos', 'Productos'), ('servicios', 'Servicios'), ('ambos', 'Productos y Servicios')], max_length=20, verbose_name='Tipo de Proveedor')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente')], default='activo', max_length=10, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('categorias', models.ManyToManyField(blank=True, related_name='proveedores', to='categorias.categoria', verbose_name='Categorías de Productos')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='proveedores.proveedor'),
        ),
        migrations.CreateModel(
            name='ContactoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('tipo_contacto', models.CharField(choices=[('principal', 'Contacto Principal'), ('ventas', 'Ventas'), ('soporte', 'Soporte Técnico'), ('administracion', 'Administración')], max_length=15, verbose_name='Tipo de Contacto')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Contacto Principal')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Contacto de Proveedor',
                'verbose_name_plural': 'Contactos de Proveedores',
            },
        ),
    ]
