# Generated by Django 5.2.3 on 2025-11-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizaciones/logos/'),
        ),
    ]
