# Generated by Django 5.2.3 on 2025-11-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0002_organizacion_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('user', 'User'), ('cajero', 'Cajero')], default='user', max_length=20),
        ),
    ]
